# https://github.com/paritytech/parity/wiki/Configuring-Parity
[parity]
chain = "chain.json"
[network]
min_peers = 0
max_peers = 0
[mining]
reseal_min_period = 0
[rpc]
cors = ["*"]
[websockets]
origins = ["localhost:8080"]
