version: 2
jobs:
  build:
    docker:
      - image: leeaandrob/centos-paratii
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
       - run: yarn install --pure-lockfile
       - run: npm install
       - run: npm install web3@1.0.0-beta.29 --save
       - save_cache:
           paths:
             - node_modules
           key: v1-dependencies-{{ checksum "package-lock.json" }}
       - run: yarn run quality
       - run: yarn run unit-test
       - run:
           command: yarn run parity
           background: true
       - run:
           command: yarn run build:dev
           background: true
       - run:
           command: yarn run server:dev
           background: true
       - run: yarn run chimp-test
       - run:
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               yarn run build
             fi
       - deploy:
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               ./deploy.sh production
             fi
             if [ "${CIRCLE_BRANCH}" == "dev" ]; then
               ./deploy.sh staging
             fi
