version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: bash <(curl https://get.parity.io -Lk)      
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run quality
      - run: npm run unit-test
      - run:
          command: npm run dev
          background: true
      - run: npm run chimp-test
      - run: npm run build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh production
            fi
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ./deploy.sh staging
            fi
