version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: bash <(curl https://get.parity.io -Lk)
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run quality
      - run: yarn run unit-test
      - run:
          command: yarn run parity
          background: true
      - run:
          command: yarn run build:dev
          background: true
      - run: yarn run chimp-test
      - run: yarn run build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh production
            fi
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ./deploy.sh staging
            fi
