version: 2
jobs:
  build:
    docker:
      - image: leeaandrob/paratii-portal:0.0.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: yarn run quality
      - run: yarn run unit-test
      - run:
          command: yarn run parity
          background: true
      - run:
          command: yarn run build:dev
          background: true
      - run:
          command: yarn run server:dev
          background: true
      - run: node src/scripts/waitForServer.js
      - run: yarn run chimp-test
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run build
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh production
            fi
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ./deploy.sh staging
            fi
