version: 2.0

jobs:
  install_dependencies:
    docker:
      - image: leeaandrob/paratii-portal:0.0.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  quality:
    docker:
      - image: leeaandrob/paratii-portal:0.0.6
      - image: circleci/mongo:latest
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run quality

  unit_test:
    docker:
      - image: leeaandrob/paratii-portal:0.0.6
      - image: circleci/mongo:latest
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run unit-test-circleci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - quality:
          requires:
            - install_dependencies
      - unit_test:
          requires:
            - install_dependencies
